name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: Menula-De-Silva
          outputs: dist/github-contribution-grid-snake.svg

      - uses: actions/upload-artifact@v2
        with:
          name: snake-artifact
          path: dist
